stages:
  - build
  - merge


test:
  tags:
    - backend
  stage: build
  script:
    - dotnet test 
  only:
    - master
  image: mcr.microsoft.com/dotnet/nightly/sdk:7.0

build:
  tags:
    - backend
  image: docker:20.10.16
  stage: build
  services:
    - docker:20.10.16-dind
  script:
    - echo "dckr_pat_OjU46U862sGLHCGEEYw6StC5zDo" | docker login $DOCKERHUB_URL -u digitalroseuwu --password-stdin
    # - docker login $DOCKERHUB_URL -u digitalroseuwu-p dckr_pat_OjU46U862sGLHCGEEYw6StC5zDo
    - docker build . -t digitalroseuwu/div-sound-backend:latest -f ./DIV-SOUND-backend/Dockerfile
    - docker push digitalroseuwu/div-sound-backend:latest
  only:
    - master
  needs:
    - test

push_to_main:
  tags:
    - backend
  stage: merge
  script:
    - apk update
    - apk add git
    - cd $TMPDIR || exit 1
    - pat="YOUR_PAT_HERE"
    - credentials=$(echo -n ":$pat" | base64)
    - git clone https://r.vanleeuwen:glpat-jShPpr5qPgUc4zso_SN1@git.digitalindividuals.com/rvleeuwen/div-sound-backend.git || exit 1
    - cd div-sound-backend || exit 1
    - echo "$buildmessage"
    - echo "merging from Development to main"
    - mergeMessage=$(git merge origin/Development -X theirs -m "$buildmessage")

  only:
    - master
  needs:
    - test