stages:
  - build

variables:
  Solution_Name: "DIV-SOUND-backend.sln"
  Test_Project_Path: "div-sound-backend/UnitTest.csproj"

install_packages:
  tags:
    - backend
  only:
    - master
  stage:
    build
  script:
    - apk add dotnet7-sdk 
    - apk add --update docker openrc
    - service docker start

build:
  tags:
    - backend
  stage: build
  script:
    - dotnet test $Test_Project_Path
  only:
    - master

docker_build:
  tags:
    - backend
  stage: build
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker build . -t testwebapp:latest -f ./testwebapp/Dockerfile
    - docker tag testwebapp:latest "$CI_REGISTRY_IMAGE:testwebapp-latest"
    - docker push "$CI_REGISTRY_IMAGE:testwebapp-latest"
  only:
    - master
