stages:
  - build

variables:
  Solution_Name: "DIV-SOUND-backend.sln"
  Test_Project_Path: UnitTest/UnitTest.csproj"


build:
  tags:
    - backend
  stage: build
  script:
    - ls DIV-SOUND-backend
    - pwd
    - dotnet test $Test_Project_Path
  only:
    - master
  image: mcr.microsoft.com/dotnet/nightly/sdk:7.0

docker_build:
  tags:
    - backend
  stage: build
  script:
    ls
    pwd
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker build . -t testwebapp:latest -f ./testwebapp/Dockerfile
    - docker tag testwebapp:latest "$CI_REGISTRY_IMAGE:testwebapp-latest"
    - docker push "$CI_REGISTRY_IMAGE:testwebapp-latest"
  only:
    - master
  needs:
    - build
