stages:
  - build

variables:
  Solution_Name: "DIV-SOUND-backend.sln"
  Test_Project_Path: UnitTest/UnitTest.csproj"


test:
  tags:
    - backend
  stage: build
  script:
    - ls DIV-SOUND-backend
    - pwd
    - dotnet test $Test_Project_Path
  only:
    - master
  image: mcr.microsoft.com/dotnet/nightly/sdk:7.0

build:
  tags:
    - backend
  image: docker:20.10.16
  stage: build
  services:
    - docker:20.10.16-dind
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD 
    - docker build . -t $CI_REGISTRY/:latest -f ./DIV-SOUND-backend/Dockerfile
    - docker push $CI_REGISTRY/:latest
  only:
    - master
  needs:
    - test
