stages:
  - build
  - merge


test:
  tags:
    - backend
  stage: build
  script:
    - dotnet test 
  only:
    - master
  image: mcr.microsoft.com/dotnet/nightly/sdk:7.0

build:
  tags:
    - backend
  image: docker:20.10.16
  stage: build
  services:
    - docker:20.10.16-dind
  script:
    - echo "dckr_pat_OjU46U862sGLHCGEEYw6StC5zDo" | docker login $DOCKERHUB_URL -u digitalroseuwu --password-stdin
    # - docker login $DOCKERHUB_URL -u digitalroseuwu-p dckr_pat_OjU46U862sGLHCGEEYw6StC5zDo
    - docker build . -t digitalroseuwu/div-sound-backend:latest -f ./DIV-SOUND-backend/Dockerfile
    - docker push digitalroseuwu/div-sound-backend:latest
  only:
    - master
  needs:
    - test

push_to_main:
  stage: merge
  script:
    - git checkout main
    - git merge master
    - git push origin main
  only:
    - master
  needs:
    - test